blueprint:
  name: Philips Hue Dimmer switch [tg]
  description: "Automation for Hue Dimmer Switch Remote"
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        device:
          filter:
            integration: hue
            model: BSB002

trigger:
  - platform: state
    entity_id: !input motion_sensor
action:
  - service: >
      "haaa"
    target: !input motion_sensor