blueprint:
  name: Philips Hue Dimmer switch [tg]
  description: "Automation for Hue Dimmer Switch Remote"
  domain: "automation"
  input:
    motion_sensor:
      target_light:
        name: target light
  trigger:
    - platform: state
      entity_id: !input motion_sensor