blueprint:
  name: Philips Hue Dimmer switch [tg]
  description: "Automation for Hue Dimmer Switch Remote"
  domain: automation
  input:
    dimmer_switch:
      name: Dimmer Switch (Remote Control)
      selector:
        device:
          filter:
          - integration: hue
            model: RWL021
          - integration: hue
            model: "Hue dimmer switch (RWL021)"

trigger:
  - platform: state
    entity_id: !input dimmer_switch
action:
  - service: >
      "haaa"
    target: !input dimmer_switch