blueprint:
  name: Philips Hue Dimmer switch [tg]
  description: "Automation for Hue Dimmer Switch Remote"
  domain: automation
  input:
    dimmer_switch:
      name: Dimmer Switch (Remote Control)
      selector:
        device:
          filter:
          - integration: hue
            model: RWL021
          - integration: hue
            model: "Hue dimmer switch (RWL021)"
    btn1_press:
      name: Button 1 (ON) press
      description: Action to run
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: hue_event
    event_data:
      device_id: !input dimmer_switch

action:
  - variables:
      # interaction_id: '{{ trigger.event.data.id }}'
      # interaction_deviceid: '{{ trigger.event.data.device_id }}'
      interaction_type: '{{ trigger.event.data.type }}'
      interaction_button: '{{ trigger.event.data.subtype }}'
  - service: notify.mobile_app
    data:
      message: 'Test DeviceID: {{ interaction_deviceid }} TYPE: {{ interaction_type }} BUTTON#: {{ interaction_button }}'